### ISSUE TITLE
Find alternative to Google Data Studio

### ISSUE THREAD

**Issue by KrauseFx** [KrauseFx/FxLifeSheet#34]
A few things that I don't like about it:

- Only 3 dimensions at pivot tables
- No way to customize the heatmap for pivot tables, in particular:
  - `from` and `to` color, they only support one color
  - No way to have the color be calculated based on the row/column, so what ends up happening is that I can't render `boolean` values with `range` values or `number` values
- Generally seems pretty limited actually
- Sometimes it just resets sorting
- No good way to fetch screenshots/reports via an API, so I can't get them via Telegram. Daily/Weekly email reports are good enough though I guess

**Comment by KrauseFx** [comment]
James sent me https://d3js.org/, this looks promising, worth exploring for sure

**Comment by KrauseFx** [comment]
Sofia told me about https://www.stata.com/, need to look into this

**Comment by KrauseFx** [comment]
https://www.tableau.com/

**Comment by KrauseFx** [comment]
This is very interesting, Google supports running d3 directly on their platform https://www.benlcollins.com/spreadsheets/d3-google-sheets/

**Comment by KrauseFx** [comment]
Ok, I actually realized, I don't want to write JS code just to render graphs, that won't be sustainable, I need something like Google Data Studio, but a more advanced version of it

**Comment by eercanayar** [comment]
Hi there,

I'm coming from the [Google API OAuth twitter discussion](https://twitter.com/KrauseFx/status/1217348314955304960). Maybe it's time to migrate the solution to a cloud architecture. **Microsoft Power BI** or **Amazon Quicksight** can easily overcome these visualization needs. If we go with AWS (which I'm certified so I can help a lot) a PostgreSQL server can be the the time series database, Quicksight can pull data from PostgreSQL. 

I'm aware that this needs almost refactor everything, but it's not possible to use Google Sheets or a similar thing as a data source of these kind of advanced analytics tools.

**Comment by skywinder** [comment]
> James sent me https://d3js.org/, this looks promising, worth exploring for sure

Just have in mind this request, and came to suggest d3 :)
I will test, how it works with the data,  it looks that it fits for many cases out of the box!🚀

**Comment by giansegato** [comment]
Ciao Felix.

Have you considered [Redash](https://redash.io/)? It's open source, self hosted and pretty solid.

**Comment by KrauseFx** [comment]
@giansegato Thanks, used it at work, might be a good candidate 👍

**Comment by swissmanu** [comment]
could https://superset.apache.org/ be a candidate as well?

**Comment by swissmanu** [comment]
> could https://superset.apache.org/ be a candidate as well?

here are some first results using a superset instance running in my k8s cluster:

![image](https://user-images.githubusercontent.com/170832/108709750-6ee10080-7513-11eb-9ab5-5a28c900cb35.png)

(not much data present yet... but promising nonetheless :) )

**Comment by KrauseFx** [comment]
This will be implemented with https://github.com/KrauseFx/FxLifeSheet/pull/74

**Comment by KrauseFx** [comment]
This is complete with https://github.com/KrauseFx/krausefx.com/pull/27
