### ISSUE TITLE
Feature Suggestion new command

### ISSUE THREAD

**Issue by techinpark** [KrauseFx/FxLifeSheet#54]
@KrauseFx Thanks for great project!  this is very useful for me. 
I want to suggest feature for writing `breakfast`, `lunch`, `dinner` 

### Steps 
- user typing `lunch`  and say what did ate today  to bot. 
- send photo 
- google_sheet insert image. 

Thanks!

**Comment by KrauseFx** [comment]
You can do that using your own json file, currently no support for photos though

**Comment by KrauseFx** [comment]
Closing this for now, as I'm not gonna work on this. Thanks for the suggestion though
