### ISSUE TITLE
Status of Project?

### ISSUE THREAD

**Issue by JakeCasey** [KrauseFx/FxLifeSheet#72]
Hey! I'm sure you're very busy but I'm just curious where you're at with this guy. I just started using it maybe two days ago and it looks like it's working pretty well and could see myself using it into the future. Might be running into a bug w/ locations and some messages out of order, but I could see myself contributing to some of these other issues that you have in here. I like the idea of having a 'how good did I do today' based on some of the metrics, for example.

Just curious where you're at w/ it.

Thanks for the cool project. Really enjoying the implementation of it.

**Comment by KrauseFx** [comment]
Hey thanks for the message, sorry I got all GitHub notifications off. The project is still active, I'm using it every day, and plan on building more stuff on top of it. I'll update the Issues soon to reflect the current status

**Comment by KrauseFx** [comment]
Gonna close this issue
